import type { Config } from "tailwindcss";

const config: Omit<Config, "content"> = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#b0c6ff",
        "primary-container": "#558dff",
        "on-primary": "#002d6e",
        secondary: "#d0bcff",
        "secondary-container": "#571bc1",
        "on-secondary": "#381e72",
        "on-secondary-container": "#c4abff",
        tertiary: "#efb8c8",
        "tertiary-container": "#633b48",
        background: "#131313",
        surface: "#131313",
        "surface-container": "#201f1f",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#c2c6d7",
        outline: "#8c9aaa",
        "outline-variant": "#3f4759",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        success: "#6ee7b7",
        warning: "#fcd34d",
        "purple-glow": "rgba(85, 22, 190, 0.15)",
        "blue-glow": "rgba(0, 88, 202, 0.1)",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["Geist", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "4rem", fontWeight: "700" }],
        "display-md": ["2.8rem", { lineHeight: "3.25rem", fontWeight: "700" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", fontWeight: "600" }],
        "headline-md": ["1.75rem", { lineHeight: "2.25rem", fontWeight: "600" }],
        "headline-sm": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "title-lg": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "500" }],
        "title-md": ["1.125rem", { lineHeight: "1.5rem", fontWeight: "500" }],
        "title-sm": ["0.975rem", { lineHeight: "1.375rem", fontWeight: "500" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "body-sm": ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", fontWeight: "500" }],
        "label-sm": ["0.6875rem", { lineHeight: "1rem", fontWeight: "500" }],
        "label-xs": ["0.5rem", { lineHeight: "0.75rem", fontWeight: "500" }],
      },
      spacing: {
        "4xs": "0.125rem",
        "3xs": "0.25rem",
        "2xs": "0.375rem",
        xs: "0.5rem",
        sm: "0.75rem",
        md: "1rem",
        lg: "1.25rem",
        xl: "1.5rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        "4xl": "3rem",
      },
      borderRadius: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
      },
      backgroundImage: {
        "mesh-gradient":
          "radial-gradient(at 0% 0%, rgba(85, 22, 190, 0.15) 0px, transparent 50%), radial-gradient(at 100% 100%, rgba(0, 88, 202, 0.1) 0px, transparent 50%)",
        "ai-glow":
          "radial-gradient(ellipse at 50% 50%, rgba(85, 141, 255, 0.15) 0%, transparent 70%)",
        "gradient-primary": "linear-gradient(135deg, #b0c6ff 0%, #d0bcff 100%)",
        "gradient-surface":
          "linear-gradient(180deg, rgba(32, 31, 31, 0.8) 0%, rgba(19, 19, 19, 0.95) 100%)",
      },
      boxShadow: {
        glass: "0 8px 32px rgba(0, 0, 0, 0.4)",
        "glass-sm": "0 4px 16px rgba(0, 0, 0, 0.3)",
        "glow-primary": "0 0 20px rgba(176, 198, 255, 0.2)",
        "glow-secondary": "0 0 20px rgba(208, 188, 255, 0.2)",
        "glow-lg": "0 0 40px rgba(85, 141, 255, 0.25)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { transform: "translateX(-10px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "scale-in": {
          from: { transform: "scale(0.95)", opacity: "0" },
          to: { transform: "scale(1)", opacity: "1" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "glow-pulse": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(176, 198, 255, 0.2)" },
          "50%": { boxShadow: "0 0 40px rgba(176, 198, 255, 0.4)" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "slide-in-right": "slide-in-right 0.25s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        shimmer: "shimmer 2s linear infinite",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
      },
    },
  },
};

export default config;
